### PR TITLE
Update nightlog sync

### LINKED ISSUE #42: Updated NightLog Structure
We have streamlined the NightLog and it's output files.

The following changes need to be made to `desi_nightlog_transfer_kpno.txt` and `desi_nightlog_transfer_nersc.txt`:

**Remove** the following folders:
DataQualityAssessment
OperationsScientist
OtherInput

**Add** following folder:
Observers

### PR DESCRIPTION
**Pull request by weaverba137**
This PR fixes #42.

### CODE REVIEW

**Comment by weaverba137** [comment]
@parfa30, the new code is installed at NERSC.  I want to make sure this works for at least one night before merging.  I did check that 20210913 is up-to-date.

**Comment by weaverba137** [comment]
I also updated 20210912.

**Comment by weaverba137** [comment]
@parfa30, please confirm that nightlog is syncing correctly.  I'd like to merge this soon.

**Comment by parfa30** [comment]
Looks good to me. Everything is being transferred as expected. Thank you.

**Comment by weaverba137** [comment]
@parfa30, please do not close pull requests before merging.

**Pull request merged**
